### PR TITLE
fix: use button tag and native tabindex for clear button

### PR DESCRIPTION
**Pull request by vtx-anton-chashchin**
## Summary by CodeRabbit

- **新特性**
  - 清除图标从 `<span>` 元素更改为 `<button>` 元素，提高了可访问性和交互性。
  
- **样式**
  - 更新了 `.rc-input-clear-icon` 的样式，移除了填充、背景和边框。

- **测试**
  - 重新组织了 `BaseInput` 组件的测试，增加了多个清除输入的交互场景。

### CODE REVIEW

**Comment by mellis481** [comment]
@afc163 @MadCcc @zombieJ Can you please review this PR? It's an important a11y improvement that my team needs. Thanks!

**Comment by mellis481** [comment]
@afc163 @MadCcc @zombieJ bump

**Comment by mellis481** [comment]
@afc163 @MadCcc @zombieJ Can you please merge this PR?

**Comment by afc163** [comment]
https://github.com/react-component/input/releases/tag/v1.7.0

**Pull request merged**
